[package]
name = "ssb-rs"
version = "0.1.0"
authors = ["Julian Maingot <julianmaingot@gmail.com>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.1"
serde = "1.0.89"
serde_json = "1.0.39"
base64 = "0.10.1"
